"""Auto-generated Apr 24, 2026 slate scaffold from live schedule + odds."""

from __future__ import annotations

REPORT_DATE = "2026-04-24"
CANVAS_SLUG = "apr24"


def make_sp_profile(xera: float) -> list[list[str]]:
    """Minimal Baseball Savant-style table; xERA is parsed by game_model.parse_xera."""
    return [
        ["ERA / xERA", f"4.60 / {xera:.2f}"],
        ["xwOBA allowed", ".335"],
        ["K%tile", "52"],
        ["Whiff%tile", "48"],
        ["Chase%tile", "52"],
        ["Top pitch", "Mix / multi"],
    ]


GAME_SPECS: list[dict] = [
    {
        "away": "DET",
        "home": "CIN",
        "time_et": "6:40 PM",
        "away_a": -118,
        "home_a": -102,
        "weather": "Live weather via compute",
        "run_env": "Medium",
        "away_xera": 4.15,
        "home_xera": 4.15,
        "analyst_confidence": "Medium",
        "rationale": "Auto-generated live scaffold from MLB schedule + market odds: Framber Valdez vs Andrew Abbott. Run compute to refresh lineups, weather, and model outputs before staking.",
        "extra_flags": ["auto_scaffold_live_odds"],
    },
    {
        "away": "BOS",
        "home": "BAL",
        "time_et": "7:05 PM",
        "away_a": 102,
        "home_a": -120,
        "weather": "Live weather via compute",
        "run_env": "Medium",
        "away_xera": 4.15,
        "home_xera": 4.15,
        "analyst_confidence": "Medium",
        "rationale": "Auto-generated live scaffold from MLB schedule + market odds: Brayan Bello vs Brandon Young. Run compute to refresh lineups, weather, and model outputs before staking.",
        "extra_flags": ["auto_scaffold_live_odds"],
    },
    {
        "away": "CLE",
        "home": "TOR",
        "time_et": "7:07 PM",
        "away_a": -125,
        "home_a": 105,
        "weather": "Live weather via compute",
        "run_env": "Medium",
        "away_xera": 4.15,
        "home_xera": 4.15,
        "analyst_confidence": "Medium",
        "rationale": "Auto-generated live scaffold from MLB schedule + market odds: Gavin Williams vs Max Scherzer. Run compute to refresh lineups, weather, and model outputs before staking.",
        "extra_flags": ["auto_scaffold_live_odds"],
    },
    {
        "away": "COL",
        "home": "NYM",
        "time_et": "7:10 PM",
        "away_a": 175,
        "home_a": -210,
        "weather": "Live weather via compute",
        "run_env": "Medium",
        "away_xera": 4.15,
        "home_xera": 4.15,
        "analyst_confidence": "Medium",
        "rationale": "Auto-generated live scaffold from MLB schedule + market odds: Michael Lorenzen vs Freddy Peralta. Run compute to refresh lineups, weather, and model outputs before staking.",
        "extra_flags": ["auto_scaffold_live_odds"],
    },
    {
        "away": "MIN",
        "home": "TB",
        "time_et": "7:10 PM",
        "away_a": 115,
        "home_a": -138,
        "weather": "Live weather via compute",
        "run_env": "Medium",
        "away_xera": 4.15,
        "home_xera": 4.15,
        "analyst_confidence": "Medium",
        "rationale": "Auto-generated live scaffold from MLB schedule + market odds: Taj Bradley vs Drew Rasmussen. Run compute to refresh lineups, weather, and model outputs before staking.",
        "extra_flags": ["auto_scaffold_live_odds"],
    },
    {
        "away": "PHI",
        "home": "ATL",
        "time_et": "7:15 PM",
        "away_a": 130,
        "home_a": -155,
        "weather": "Live weather via compute",
        "run_env": "Medium",
        "away_xera": 4.15,
        "home_xera": 4.15,
        "analyst_confidence": "Medium",
        "rationale": "Auto-generated live scaffold from MLB schedule + market odds: Andrew Painter vs Grant Holmes. Run compute to refresh lineups, weather, and model outputs before staking.",
        "extra_flags": ["auto_scaffold_live_odds"],
    },
    {
        "away": "LAA",
        "home": "KC",
        "time_et": "7:40 PM",
        "away_a": -110,
        "home_a": -110,
        "weather": "Live weather via compute",
        "run_env": "Medium",
        "away_xera": 4.15,
        "home_xera": 4.15,
        "analyst_confidence": "Medium",
        "rationale": "Auto-generated live scaffold from MLB schedule + market odds: Yusei Kikuchi vs Noah Cameron. Run compute to refresh lineups, weather, and model outputs before staking.",
        "extra_flags": ["auto_scaffold_live_odds"],
    },
    {
        "away": "WSH",
        "home": "CWS",
        "time_et": "7:40 PM",
        "away_a": 105,
        "home_a": -125,
        "weather": "Live weather via compute",
        "run_env": "Medium",
        "away_xera": 4.15,
        "home_xera": 4.15,
        "analyst_confidence": "Medium",
        "rationale": "Auto-generated live scaffold from MLB schedule + market odds: PJ Poulin vs Bryan Hudson. Run compute to refresh lineups, weather, and model outputs before staking.",
        "extra_flags": ["auto_scaffold_live_odds"],
    },
    {
        "away": "PIT",
        "home": "MIL",
        "time_et": "7:40 PM",
        "away_a": -120,
        "home_a": 102,
        "weather": "Live weather via compute",
        "run_env": "Medium",
        "away_xera": 4.15,
        "home_xera": 4.15,
        "analyst_confidence": "Medium",
        "rationale": "Auto-generated live scaffold from MLB schedule + market odds: Paul Skenes vs Brandon Woodruff. Run compute to refresh lineups, weather, and model outputs before staking.",
        "extra_flags": ["auto_scaffold_live_odds"],
    },
    {
        "away": "ATH",
        "home": "TEX",
        "time_et": "8:05 PM",
        "away_a": 117,
        "home_a": -140,
        "weather": "Live weather via compute",
        "run_env": "Medium",
        "away_xera": 4.15,
        "home_xera": 4.15,
        "analyst_confidence": "Medium",
        "rationale": "Auto-generated live scaffold from MLB schedule + market odds: Luis Severino vs Nathan Eovaldi. Run compute to refresh lineups, weather, and model outputs before staking.",
        "extra_flags": ["auto_scaffold_live_odds"],
    },
    {
        "away": "NYY",
        "home": "HOU",
        "time_et": "8:10 PM",
        "away_a": -154,
        "home_a": 130,
        "weather": "Live weather via compute",
        "run_env": "Medium",
        "away_xera": 4.15,
        "home_xera": 4.15,
        "analyst_confidence": "Medium",
        "rationale": "Auto-generated live scaffold from MLB schedule + market odds: Will Warren vs Lance McCullers Jr.. Run compute to refresh lineups, weather, and model outputs before staking.",
        "extra_flags": ["auto_scaffold_live_odds"],
    },
    {
        "away": "SEA",
        "home": "STL",
        "time_et": "8:15 PM",
        "away_a": -145,
        "home_a": 124,
        "weather": "Live weather via compute",
        "run_env": "Medium",
        "away_xera": 4.15,
        "home_xera": 4.15,
        "analyst_confidence": "Medium",
        "rationale": "Auto-generated live scaffold from MLB schedule + market odds: George Kirby vs Andre Pallante. Run compute to refresh lineups, weather, and model outputs before staking.",
        "extra_flags": ["auto_scaffold_live_odds"],
    },
    {
        "away": "CHC",
        "home": "LAD",
        "time_et": "10:15 PM",
        "away_a": 138,
        "home_a": -160,
        "weather": "Live weather via compute",
        "run_env": "Medium",
        "away_xera": 4.15,
        "home_xera": 4.15,
        "analyst_confidence": "Medium",
        "rationale": "Auto-generated live scaffold from MLB schedule + market odds: Jameson Taillon vs Emmet Sheehan. Run compute to refresh lineups, weather, and model outputs before staking.",
        "extra_flags": ["auto_scaffold_live_odds"],
    },
    {
        "away": "MIA",
        "home": "SF",
        "time_et": "10:15 PM",
        "away_a": -115,
        "home_a": -105,
        "weather": "Live weather via compute",
        "run_env": "Medium",
        "away_xera": 4.15,
        "home_xera": 4.15,
        "analyst_confidence": "Medium",
        "rationale": "Auto-generated live scaffold from MLB schedule + market odds: Sandy Alcantara vs Adrian Houser. Run compute to refresh lineups, weather, and model outputs before staking.",
        "extra_flags": ["auto_scaffold_live_odds"],
    },
]
