"""Auto-generated Apr 30, 2026 slate scaffold from live schedule + odds."""

from __future__ import annotations

REPORT_DATE = "2026-04-30"
CANVAS_SLUG = "apr30"


def make_sp_profile(xera: float) -> list[list[str]]:
    """Minimal Baseball Savant-style table; xERA is parsed by game_model.parse_xera."""
    return [
        ["ERA / xERA", f"4.60 / {xera:.2f}"],
        ["xwOBA allowed", ".335"],
        ["K%tile", "52"],
        ["Whiff%tile", "48"],
        ["Chase%tile", "52"],
        ["Top pitch", "Mix / multi"],
    ]


GAME_SPECS: list[dict] = [
    {
        "away": "DET",
        "home": "ATL",
        "time_et": "12:15 PM",
        "away_a": None,
        "home_a": None,
        "weather": "Live weather via compute",
        "run_env": "Medium",
        "away_xera": 4.15,
        "home_xera": 4.15,
        "analyst_confidence": "Medium",
        "rationale": "Auto-generated live scaffold from MLB schedule + market odds: Framber Valdez vs Bryce Elder. Run compute to refresh lineups, weather, and model outputs before staking.",
        "extra_flags": ["auto_scaffold_live_odds", "market_odds_unavailable"],
    },
    {
        "away": "STL",
        "home": "PIT",
        "time_et": "12:35 PM",
        "away_a": None,
        "home_a": None,
        "weather": "Live weather via compute",
        "run_env": "Medium",
        "away_xera": 4.15,
        "home_xera": 4.15,
        "analyst_confidence": "Medium",
        "rationale": "Auto-generated live scaffold from MLB schedule + market odds: Hunter Dobbins vs Paul Skenes. Run compute to refresh lineups, weather, and model outputs before staking.",
        "extra_flags": ["auto_scaffold_live_odds", "market_odds_unavailable"],
    },
    {
        "away": "COL",
        "home": "CIN",
        "time_et": "12:40 PM",
        "away_a": None,
        "home_a": None,
        "weather": "Live weather via compute",
        "run_env": "Medium",
        "away_xera": 4.15,
        "home_xera": 4.15,
        "analyst_confidence": "Medium",
        "rationale": "Auto-generated live scaffold from MLB schedule + market odds: Michael Lorenzen vs Andrew Abbott. Run compute to refresh lineups, weather, and model outputs before staking.",
        "extra_flags": ["auto_scaffold_live_odds", "market_odds_unavailable"],
    },
    {
        "away": "WSH",
        "home": "NYM",
        "time_et": "1:10 PM",
        "away_a": None,
        "home_a": None,
        "weather": "Live weather via compute",
        "run_env": "Medium",
        "away_xera": 4.15,
        "home_xera": 4.15,
        "analyst_confidence": "Medium",
        "rationale": "Auto-generated live scaffold from MLB schedule + market odds: Miles Mikolas vs Freddy Peralta. Run compute to refresh lineups, weather, and model outputs before staking.",
        "extra_flags": ["auto_scaffold_live_odds", "market_odds_unavailable"],
    },
    {
        "away": "AZ",
        "home": "MIL",
        "time_et": "1:40 PM",
        "away_a": 110,
        "home_a": -125,
        "weather": "Live weather via compute",
        "run_env": "Medium",
        "away_xera": 4.15,
        "home_xera": 4.15,
        "analyst_confidence": "Medium",
        "rationale": "Auto-generated live scaffold from MLB schedule + market odds: Michael Soroka vs Brandon Woodruff. Run compute to refresh lineups, weather, and model outputs before staking.",
        "extra_flags": ["auto_scaffold_live_odds"],
    },
    {
        "away": "KC",
        "home": "ATH",
        "time_et": "3:05 PM",
        "away_a": 105,
        "home_a": -125,
        "weather": "Live weather via compute",
        "run_env": "Medium",
        "away_xera": 4.15,
        "home_xera": 4.15,
        "analyst_confidence": "Medium",
        "rationale": "Auto-generated live scaffold from MLB schedule + market odds: Noah Cameron vs Jeffrey Springs. Run compute to refresh lineups, weather, and model outputs before staking.",
        "extra_flags": ["auto_scaffold_live_odds"],
    },
    {
        "away": "SF",
        "home": "PHI",
        "time_et": "5:35 PM",
        "away_a": 120,
        "home_a": -145,
        "weather": "Live weather via compute",
        "run_env": "Medium",
        "away_xera": 4.15,
        "home_xera": 4.15,
        "analyst_confidence": "Low",
        "rationale": "Auto-generated live scaffold from MLB schedule + market odds: TBD vs TBD. Run compute to refresh lineups, weather, and model outputs before staking.",
        "extra_flags": ["auto_scaffold_live_odds", "probable_pitcher_missing"],
    },
    {
        "away": "TOR",
        "home": "MIN",
        "time_et": "7:40 PM",
        "away_a": -135,
        "home_a": 115,
        "weather": "Live weather via compute",
        "run_env": "Medium",
        "away_xera": 4.15,
        "home_xera": 4.15,
        "analyst_confidence": "Medium",
        "rationale": "Auto-generated live scaffold from MLB schedule + market odds: Kevin Gausman vs Bailey Ober. Run compute to refresh lineups, weather, and model outputs before staking.",
        "extra_flags": ["auto_scaffold_live_odds"],
    },
]
